### ISSUE TITLE
wildly different results vs tradingview

### ISSUE THREAD

**Issue by mmaestrini** [ixjb94/indicators#10]
Hi there

Any idea why the exact same underlying data can result in such different outcomes for even simpler things like regular emas?

![image](https://github.com/ixjb94/indicators/assets/66750632/bb1d483d-9369-46e0-b0fd-ec5f54938742)

**Comment by ixjb94** [comment]
@mmaestrini Hey,
I've made a Repository to test the EMA 10 from TradingView and @ixjb94/indicators.

[Indicators Data Test](https://github.com/ixjb94/indicators-data-test)

**Comment by ixjb94** [comment]
Also I've just made a Jest test for the library.
You can check it out.

https://github.com/ixjb94/indicators#tests-jest
