### ISSUE TITLE
Paid Consultancy Project

### ISSUE THREAD

**Issue by luxsush** [ixjb94/indicators#13]
Hi 

Trust you are doing good.  We are a commercial project looking for talents like yourself.

How can we contact you?  We want to avail your services for a commercial project. We are interested in similar work but somewhat very different which focuses on indicator optimizations

You can email us at luxsush@altmails.com

**Comment by ixjb94** [comment]
@luxsush Hi.
Thanks for the offer, but rn I don't need a job.

**Comment by luxsush** [comment]
Sure enough. It was not a full-time job offer but rather a freelance project. Anyway... in case you ever change your mind, you know where to reach me.  Given the synergies between this open-source project and the one I am referring to, your open-source project will also immensely benefit from this approach. 

So a 30,000 ft overview. The project involves converting technical indicators to compute on every tick rather than in a loop. So when you add a new indicator, doing the loop is fine. But on streaming ticks, you don't want to run the loop across the entire history on every tick.  At this point, you need an efficient method to just calculate the last point and append it to your array.

If this project sounds interesting to you, we can discuss collaborations
