### ISSUE TITLE
Missing indicators: cosh and qstick ?

### ISSUE THREAD

**Issue by erdemozveren** [ixjb94/indicators#17]
Hi, i just i noticed `cosh - Vector Hyperbolic Cosine` and `qstick` are not implemented and marked as available in readme.md, fyi.

**Comment by ixjb94** [comment]
@erdemozveren Hi 😊,    
Thanks a lot for the report.    
I've updated the code: removed cosh from readme    
and added qstick 🤗.    
https://github.com/ixjb94/indicators/commit/205cf177124e120578faadfd9ca2e6e17c875598

**Comment by erdemozveren** [comment]
Glad to help, this kind of package (no native binding or depenedency) is gold,thank you.
