### ISSUE TITLE
Questions about results and format

### ISSUE THREAD

**Issue by mmaestrini** [ixjb94/indicators#6]
Hi there

First of all thanks because this is great for those of us in TS :)

I have 2 questions:

1) Is the data returned from say `ta.rsi(close5m, rsiPeriod)` is in desc or asc order? meaning is index 0 the most recent? 
2) Why is it that the data is SO different from the tradingview indiators?

I think I am doing things correctly but please try to double check:

I fetch kline data for a good chunk (7 to 14 days) on 5 min, 15 min and 1h interval. For each of those individual datasets, I run the RSI as shown before and AO as follows: `ta.ao(high15m, low15m)`. 

The results are wildly different when i compare the numbers with the indicators on tradingview on the same coin - how come? 

RSI at index 0 on 5m tf for OPUSDT shows 29.9 ta.rsi I call but on tradingview is like 60. The last index is 67, and although closer is still quite far off id say.

Any idea?

**Comment by mmaestrini** [comment]
it seems now that i order asc the data is roughly ok comapred to the TV indicators. 

However, the stoch rsi is quite substantially off even tho I use the same period

![image](https://github.com/ixjb94/indicators/assets/66750632/b26d934e-8ea9-47e6-b68a-a72a9104487b)

**Comment by mmaestrini** [comment]
I found out i am looking for the stoch instead of stochrsi, can somone tell me what settings to use for kslow, keperiod, dperiod? k and d in trading view is 3 and kslow not sure what it is

**Comment by ixjb94** [comment]
@mmaestrini Hey,
Here is the code (pine script) for Stochastic RSI

```python
//@version=5
indicator(title="Stochastic RSI", shorttitle="Stoch RSI", format=format.price, precision=2, timeframe="", timeframe_gaps=true)

// Inputs
smoothK      = input.int(3, "K", minval=1)
smoothD      = input.int(3, "D", minval=1)
lengthRSI     = input.int(14, "RSI Length", minval=1)
lengthStoch = input.int(14, "Stochastic Length", minval=1)
src = input(close, title="RSI Source")

// Calculation
rsi1 = ta.rsi(src, lengthRSI)
k = ta.sma(ta.stoch(rsi1, rsi1, rsi1, lengthStoch), smoothK)
d = ta.sma(k, smoothD)

// Plot
plot(k, "K", color=#2962FF)
plot(d, "D", color=#FF6D00)
h0 = hline(80, "Upper Band", color=#787B86)
hline(50, "Middle Band", color=color.new(#787B86, 50))
h1 = hline(20, "Lower Band", color=#787B86)
fill(h0, h1, color=color.rgb(33, 150, 243, 90), title="Background")
```
So you can make it your own version based on the @ixjb94/indicators if you want to (follow the calculation).
Something like this:

```js
// import indicators
const rsi      = ta.rsi(...)
const stoch    = ta.stoch(...)
const k        = ta.sma(stoch, 3)
const d        = ta.sma(k, 3)
```

**Comment by mmaestrini** [comment]
@ixjb94 Awesome appreciate it! 

2 questions: 

They use the same rsi1 in each parameter of stoch. I did this: 
`let stoch5m = await ta.stoch(high5m, low5m, close5m, 14, 3, 3);`
Cause I read you should use high, low and close of your dataset?

Anyway, the next thing is that if i pass the `stoch` variable into sma, it says: 
```
Argument of type 'number[][]' is not assignable to parameter of type 'number[]'.
Type 'number[]' is not assignable to type 'number'.ts(2345)
```
stoch gives an array of array, so what should I do? 

Thank you so much for this anyway, it's awesome <3

**Comment by ixjb94** [comment]
@mmaestrini 
Stochastic gives you two outputs
```js
// @returns [stoch, stoch_ma]
```
the first one is `stoch` and the second one is `moving average stoch`
so you can do something like this:
```js
const [stoch5m, stoch5m_ma] = await ta.stoch(...)
```
here is the TradingView's Stochastic
```python
ta.stoch(source, high, low, length) → series float
```

and here is our Stochastic
```js
/**
* 
* @param high 
* @param low 
* @param close 
* @param kperiod 
* @param kslow 
* @param dperiod 
* @returns [stoch, stoch_ma]
*/
```

Also if you want to merge different datasets it's easier to use Normalized version,
because some indicators returns full length and some have gaps, 
Example:
```text
20 close, with EMA 20 (ta.ema(close, 20) -> Array(20)
```
But, RSI 14 in 20 close does have 14 gaps (null values | delay)
```text
20 close, with RSI 20 (ta.rsi(close, 14) -> Array(14 undefined + 6 value)
```

**Comment by ixjb94** [comment]
Here is the comparison between @ixjb94/indicators and TradingView
[BTCUSDT_5m_Daily: 11/June/2023 ](https://data.binance.vision/?prefix=data/futures/um/daily/klines/BTCUSDT/5m/)

First Array = %K (Blue Line) in TradingView
Second Array = %D (Orange Line) in TradingView
```js
[
    <14 empty items>,   NaN,                46.35124298315873,
    38.6527666399362,   48.59663191659839,  72.01283079390437,
    78.75862068965567,  73.72413793103549,  71.37931034482759,
    77.17241379310445,  75.51724137931033,  60.482758620690156,
    51.655172413794105, 42.3448275862079,   22.43697478991658,
    19.5798319327725,   15.6794425087109,   31.271777003482615,
    28.646748681896973, 38.04920913883967,  36.47984267453125,
    9.341199606686265,  19.46902654867171,  7.571288102262215,
    2.9411764705850882, 9.746835443038895,  16.382699868937774,
    31.84796854521885,  26.86762778505795,  22.07112970711475,
    48.01255230125566,  42.468619246863234, 21.12970711297099,
    27.210884353740994, 40.8493427704761,   32.98611111111055,
    15.22727272727438,  25.947187141215757, 12.87958115183551,
    30.921052631578576, 39.7660818713463,   29.605263157894896,
    46.49122807017728,  44.88304093567382,  83.25434439178487,
    79.80535279805517,  75.50544323483712,  85.84758942457199,
    86.31415241057397,  89.96889580093217,  87.5583203732506,
    99.62006079027357,  87.61398176291593,  88.12561334641609,
    99.7826086956527,   72.98735861610197,  72.03626220362752,
    83.61669242658387,  86.91674290942419,  73.92550143266473,
    83.20235756385199,  71.42857142857247,  81.4185814185826,
    54.63157894736995,  56.63157894737149,  43.78947368421283,
    36.63157894737149,  36.90176322418146,  31.5937940761615,
    45.55712270803987,  37.79971791255303,  56.13540197461283,
    37.62376237623732,  38.34710743801773,  29.34782608695745,
    12.021857923495096, 41.49139579350101,  27.819548872178324,
    6.265664160401345,  11.67608286252523,  10.169491525426748,
    14.18563922941988,  2.8616852146253335, 8.983799705447336,
    30.191458026510542, 21.97640117993802,  68.9165186500884,
    38.89875666074263,  4.94505494505641,   37.271750805586755,
    51.23523093448063,  38.095238095235864, 29.768041237112087,
    38.65979381443371,  57.60309278350717,  56.95876288659994,
    43.298969072163885, 36.4690721649482,   50.12886597937957,
    59.793814432988,
    ... 175 more items
  ],
  [
    <14 empty items>,   NaN,                43.272284419101894,
    43.67816091954036,  44.533547179897774, 53.08740978347966,
    66.45602780005282,  74.83186313819851,  74.62068965517292,
    74.09195402298919,  74.68965517241413,  71.05747126436833,
    62.551724137931544, 51.494252873564065, 38.812324929972874,
    28.120544769632335, 19.232083077133336, 22.17701714832201,
    25.1993227313635,   32.6559116080731,   34.391933498422645,
    27.956750473352404, 21.76335627662975,  12.12717141920674,
    9.993830373839678,  6.753100005295408,  9.690237260853927,
    19.32583461906518,  25.0327653997382,   26.928908679130522,
    32.317103264476124, 37.51743375174455,  37.2036262203633,
    30.269736904525075, 29.729978079062693, 33.682112745109215,
    29.687575536287014, 24.72019032653356,  18.01801367344188,
    23.249273641543283, 27.85557188492013,  33.43079922027326,
    38.62085769980616,  40.32651072124867,  58.20953779921199,
    69.31424604183795,  79.52171347489238,  80.38612848582143,
    82.55572835666104,  87.37687921202605,  87.94712286158558,
    92.38242565481877,  91.59745430881335,  91.7865519665352,
    91.84073460166158,  86.9651935527236,   81.60207650512741,
    76.21343774877114,  80.85656584654521,  81.4863122562243,
    81.34820063531367,  76.18547680836309,  78.68317013700239,
    69.15957726484172,  64.22724643777471,  51.684210526318125,
    45.68421052631864,  39.107605285255296, 35.04237874923819,
    38.01756000279431,  38.316878232251504, 46.49741419840195,
    43.85296075446776,  44.03542392962266,  35.10623196707087,
    26.57226381615679,  27.62035993465122,  27.110934196391504,
    25.192202942026924, 15.25376529836833,  9.370412849451139,
    12.010404539123986, 9.07227198982402,   8.677041383164216,
    14.01231431552777,  20.38388630396533,  40.36145928551235,
    43.26389216358971,  37.5867767519625,   27.038520803795286,
    31.15067889504129,  42.200739945101105, 39.699503422276216,
    35.50769104892724,  42.01030927835101,  51.07388316151362,
    52.62027491409035,  45.575601374570695, 43.29896907216391,
    48.79725085910528,
    ... 175 more items
  ]
]
```

![image](https://github.com/ixjb94/indicators/assets/121232430/5c1a6f5a-dea6-4b8c-9bf7-4cb606a26951)
![image](https://github.com/ixjb94/indicators/assets/121232430/4726938f-a64d-4ec4-9f44-db1632364ba2)
![image](https://github.com/ixjb94/indicators/assets/121232430/5e79291a-8e94-4033-abbb-8dcfbfae6941)

TradingView:
![image](https://github.com/ixjb94/indicators/assets/121232430/bbae1e9f-4c75-4a26-8a79-455ced510681)

Our data (chart by google sheet)
![image](https://github.com/ixjb94/indicators/assets/121232430/50bd0586-a6ce-4356-9b24-8846585271a1)

Data in .txt file
[data for sheet.txt](https://github.com/ixjb94/indicators/files/11749302/data.for.sheet.txt)

**Note:** our data does have 15 gaps, so if you want the exact data you should import 15 more data from the previous day

**Comment by mmaestrini** [comment]
Perfect that is amazing! Thank you so much for taking the time explaining! I appreciate it!

**Comment by mmaestrini** [comment]
Sorry forgot to ask, if the Stochastic gives you stoch and stoch_ma, isn't that then equal to k and d?

**Comment by mmaestrini** [comment]
Also i noticed that doing let stoch5m = await ta.stoch(rsi5m, rsi5m, rsi5m, 14, 3, 3); basically gives a 1:1 (at least visually) output to tradingview stoch rsi .. so it hink this is good :) 
![image](https://github.com/ixjb94/indicators/assets/66750632/f47135b1-e483-49e0-90ee-5977a1e48aa2)

**Comment by ixjb94** [comment]
Yes stoch and stoch_ma are K and D (blue and orange lines)

**Comment by mmaestrini** [comment]
@ixjb94 Thanks! Can you also confirm that the last index in the array is the most recent value?
