### ISSUE TITLE
Getting error while using the library

### ISSUE THREAD

**Issue by nishanthmekala29** [ixjb94/indicators#8]
ERROR in ./node_modules/technical-indicators/src/core/indicators.ts 10:46
Module parse failed: Unexpected token (10:46)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| 	 * @returns 
| 	 */

async normalize(originalLength: number, source: Array<number> | string, empty = NaN): Promise<Array<number>> {
| 	const diff = originalLength - source.length
| 

Getting this error when i used your library in my react.js project.

Already tried every solution mentioned here 
https://stackoverflow.com/questions/63423384/you-may-need-an-additional-loader-to-handle-the-result-of-these-loaders.

could not get out of the issue. 

It could be very helpful for me if you solve this error.

If i comment the errored code. i will get error at other code lines

**Comment by ixjb94** [comment]
@Nishanth-Besseggen Hey,
i've just installed React and here is my code
App.js
```js
import { IndicatorsNormalized } from "../node_modules/@ixjb94/indicators/dist/indicators-browser"

const closes = [1, 2, 3, 4, 5]
const ta = new IndicatorsNormalized()
ta.ema(closes, 2).then(d => console.log(d))

function App() {
  return (<h1>Hello World</h1>)
}

export default App
```

Result in browser:
```
[1, 1.6666666666666665, 2.5555555555555554, 3.518518518518518, 4.506172839506172]
```
![image](https://github.com/ixjb94/indicators/assets/121232430/2217cf4e-61c9-4261-b35f-17faf10b9196)

**Note**
if you couldn't solve the issue, you can always use the algorithm directly inside your code,    
because @ixjb94/indicators is not using any 3rd party libraries so it's easy as a Copy/Paste. example:    
EMA: 
```ts
async function ema(
	source: number[], period: number,
	size: number = source.length
) {

	const output: number[] = []
	const per = 2 / (period + 1)

	let val = source[0]
	output.push(val)

	for (let i = 1; i < size; ++i) {
		val = (source[i] - val) * per + val
		output.push(val)
	}

	return output
}
```
